spring:

  # Configuration de la source de données
  datasource:
    url: jdbc:h2:mem:job02
    driverClassName: org.h2.Driver
    username: lea
    password:

  # Configuration de la console H2 (facultatif, pour accéder à la console web H2)
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true